=== JAHNAVIJAGASANDRAM/web-devlopment/book/book.dtd
<!ELEMENT books (title,author,isbn,publisher,name,edition,price)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== JAHNAVIJAGASANDRAM/web-devlopment/book/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM "book.dtd" >
<?xml-model href="book.xsd"?>
<books>
    
        <title>zero to one</title>
        <author>peter thie</author>
        <isbn>978-0-753</isbn>
        <publisher>penguin</publisher>
        <name>help</name>
        <edition>1</edition>
        <price>20</price>

</books>
