=== JAHNAVIJAGASANDRAM/web-devlopment/xmlFiles/university/university.dtd
<!ELEMENT university (department,course,faculty,student)>
<!ELEMENT department (DeptId,DeptName,hod)>
<!ELEMENT course (courseCode,courseName,credits)>
<!ELEMENT  faculty (facultyId,name,designation,DeptId)>
<!ELEMENT  student (studentId,studentName,DeptId)>
<!ELEMENT DeptId (#PCDATA)>
<!ELEMENT DeptName (#PCDATA)>
<!ELEMENT hod (#PCDATA)>
<!ELEMENT courseCode (#PCDATA)>
<!ELEMENT  courseName (#PCDATA)>
<!ELEMENT  credits (#PCDATA)>
<!ELEMENT  facultyId (#PCDATA)>
<!ELEMENT  name (#PCDATA)>
<!ELEMENT  designation (#PCDATA)>
<!ELEMENT  studentId (#PCDATA)>
<!ELEMENT  studentName (#PCDATA)>

=== JAHNAVIJAGASANDRAM/web-devlopment/xmlFiles/university/university.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE university SYSTEM "university.dtd">
    
<university>
    <department>
        <DeptId>62</DeptId>
        <DeptName>cyber</DeptName>
        <hod>sunitha</hod>
    </department>
    <course>
        <courseCode>a62</courseCode>
        <courseName>cs</courseName>
        <credits>3</credits>
    </course>
    <faculty>
        <facultyId>62aa1</facultyId>
        <name>naresh</name>
        <designation>faculty</designation>
        <DeptId>cyber</DeptId>
    </faculty>
    <student>
        <studentId>6283</studentId>
        <studentName>jahnavi</studentName>
        <DeptId>cyber</DeptId>
    </student>

</university>
